alter table ResOrder add discount numeric(5,2) null
GO
-- init ResTable
set IDENTITY_INSERT ResTable on
go

insert into ResTable(id, code, position) values(1, 'T001', '1')
insert into ResTable(id, code, position) values(2, 'T002', '2')
insert into ResTable(id, code, position) values(3, 'T003', '3')
insert into ResTable(id, code, position) values(4, 'T004', '4')
insert into ResTable(id, code, position) values(5, 'T005', '5')
insert into ResTable(id, code, position) values(6, 'T006', '6')
insert into ResTable(id, code, position) values(7, 'T007', '7')
insert into ResTable(id, code, position) values(8, 'T008', '8')
insert into ResTable(id, code, position) values(9, 'T009', '9')
insert into ResTable(id, code, position) values(10, 'T010', '10')
insert into ResTable(id, code, position) values(11, 'T011', '11')
insert into ResTable(id, code, position) values(12, 'T012', '12')
insert into ResTable(id, code, position) values(13, 'T013', '13')
insert into ResTable(id, code, position) values(14, 'T014', '14')
insert into ResTable(id, code, position) values(15, 'T015', '15')
insert into ResTable(id, code, position) values(16, 'T016', '16')
insert into ResTable(id, code, position) values(17, 'T017', '17')
insert into ResTable(id, code, position) values(18, 'T018', '18')
insert into ResTable(id, code, position) values(19, 'T019', '19')
insert into ResTable(id, code, position) values(20, 'T020', '20')
insert into ResTable(id, code, position) values(21, 'T021', '21')
insert into ResTable(id, code, position) values(22, 'T022', '22')
insert into ResTable(id, code, position) values(23, 'T023', '23')
insert into ResTable(id, code, position) values(24, 'T024', '24')
insert into ResTable(id, code, position) values(25, 'T025', '25')
insert into ResTable(id, code, position) values(26, 'T026', '26')
insert into ResTable(id, code, position) values(27, 'T027', '27')
insert into ResTable(id, code, position) values(28, 'T028', '28')
insert into ResTable(id, code, position) values(29, 'T029', '29')
insert into ResTable(id, code, position) values(30, 'T030', '30')
insert into ResTable(id, code, position) values(31, 'T031', '31')
insert into ResTable(id, code, position) values(32, 'T032', '32')
insert into ResTable(id, code, position) values(33, 'T033', '33')
insert into ResTable(id, code, position) values(34, 'T034', '34')
insert into ResTable(id, code, position) values(35, 'T035', '35')
insert into ResTable(id, code, position) values(36, 'T036', '36')
insert into ResTable(id, code, position) values(37, 'T037', '37')
insert into ResTable(id, code, position) values(38, 'T038', '38')
insert into ResTable(id, code, position) values(39, 'T039', '39')
insert into ResTable(id, code, position) values(40, 'T040', '40')
insert into ResTable(id, code, position) values(41, 'T041', '41')
insert into ResTable(id, code, position) values(42, 'T042', '42')
insert into ResTable(id, code, position) values(43, 'T043', '43')
insert into ResTable(id, code, position) values(44, 'T044', '44')
insert into ResTable(id, code, position) values(45, 'T045', '45')
insert into ResTable(id, code, position) values(46, 'T046', '46')
insert into ResTable(id, code, position) values(47, 'T047', '47')
insert into ResTable(id, code, position) values(48, 'T048', '48')
insert into ResTable(id, code, position) values(49, 'T049', '49')
insert into ResTable(id, code, position) values(50, 'T050', '50')
go

set IDENTITY_INSERT ResTable off
go